name: automate k6
on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: install k6
        run: brew install k6
      
      - name: run code
        run: npm start

