name: automate k6
on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:
  push:
    branches: "master"

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: download k6 release binaries
        run: brew install k6

      - name: k6 test
        run: sh run.sh
     
      - name: Archive HTML Report 
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: html-report
          path: ./reports/
      - name: Cleanup
        if: ${{ always() }}
        uses: ank1traj/action-cleanup@master
